paths:
    data_path_train: "/home/s1736191/myjupyter/DiffusionMAR/Data/Isala_1/train"
    data_path_val: "/home/s1736191/myjupyter/DiffusionMAR/Data/Isala_1/val"
    save_path: "/home/s1736191/myjupyter/DiffusionMAR/Results/"
trainingparams:
    epochs: 5
    batch_size: 10
    learning_rate: 0.0001
    img_resized: 256
model:
  BB:
    params:
      mt_type: 'linear' # options {'linear', 'sin'}
      num_timesteps: 1000 # T
      max_var: 0.1 # s --> var = 2s(mt - mt^2)
      
      sample_type: 'linear' # options {'linear', 'sin'}
      sample_steps: 25
      
      loss_type: 'l1' # options {'l1', 'l2'}
      
      UNetParams:
        image_size: 256
        in_channels: 1
        model_channels: 64
        out_channels: 1
        num_res_blocks: 2
        attention_resolutions: !!python/tuple
          - 32
          - 16
          - 8
        channel_mult: !!python/tuple
          - 1
          - 2
          - 4
        conv_resample: True
        dims: 2
        num_heads: 8
        num_head_channels: 64
        use_scale_shift_norm: True
        resblock_updown: True
        use_spatial_transformer: False
        context_dim:
        condition_key: "nocond" # options {"SpatialRescaler", "first_stage", "nocond"}